apiVersion: rbac.authorization.k8s.io/v1

kind: Role

metadata:
  name: developer


rules:
  - apiGroups: [""]
    resources: ["pods"]
    verbs: ["list","get","create","update","delete"]
    resourceNames: ["blue","orange"] # For which pods we have access
  - apiGroups: [""]
    resources: ["ConfigMap"]
    verbs: ["create"]


#AFTER RUNNING THE FILE AND CREATING THE ROLE BIND THE ROLE TO THE USER

---
kind: Role
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  namespace: blue
  name: deploy-role
rules:
  - apiGroups: ["apps", "extensions"]
    resources: ["deployments"]
    verbs: ["create"]


---
kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name:  dev-user-binding

subjects:
  - kind: User
    name: dev-user
    apiGroup: rbac.authorization.k8s.io
  roleRef:
    kind: Role
    name: developer
    apiGroup: rbac.authorization.k8s.iomaster