apiVersion: v1

kind: ReplicationController

metadata:
  name: myapp-rc
  labels:
    app: myapp
    type: front-end

specs: # Replication Controller( Parent )
  template:
    metadata:
      name: myapp-pod
      labels:
        app: myapp
        type: front-end

    spec: # Pod Specifications (Child)
      containers:
        - name: nginx-container
          image: nginx

  replicas: 3 # Number of replications required

